"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {Gem,Menu,X,Phone,MapPin,Clock3,Check,Copy,MessageCircle,Sparkles,ShieldCheck,PencilRuler,Camera} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {initialDraft,indiaDate,validateDraft,prepareMessage,whatsappUrl,type RequestDraft,type EnquiryType} from "@/lib/enquiry";
import GoldRateTicker from "@/components/gold-rate-ticker";
import InstagramFeed from "@/components/instagram-feed";

const collections=[
 {id:"gold",name:"Gold Heirlooms",category:"Gold",image:"gold-heirlooms.jpeg",alt:"Traditional gold necklace with red and green accents and hanging gold motifs",line:"Tradition, beautifully reimagined.",description:"Discover traditional gold artistry for celebrations and pieces to cherish across generations. Explore finishes, proportions and details with our team.",details:["Traditional necklaces & sets","Gold finishes & personal details","BIS hallmarked gold jewellery"]},
 {id:"diamonds",name:"Diamond Icons",category:"Diamonds",image:"diamond-earring.png",alt:"Emerald-cut diamond drop earring with a floral diamond cluster top",line:"Brilliance for your every milestone.",description:"Explore diamond jewellery for meaningful gifts, engagements and everyday elegance. We can guide you through diamond shape, design and certification details wherever applicable.",details:["Diamond rings, earrings & pendants","Shape & setting guidance","Certification where applicable"]},
 {id:"bridal",name:"Bridal Grandeur",category:"Bridal",image:"gold-jewellery.png",alt:"Ornate gold bridal necklace with intricate floral filigree",line:"For the moment. For generations.",description:"Bring your bridal vision together with statement jewellery and personal guidance. Discuss your outfit, occasion and budget to explore a considered selection.",details:["Statement necklaces & bridal sets","Styling around your wedding outfit","Personal showroom consultations"]},
];
const budgets=["Discuss with the team","Under ₹50,000","₹50,000–₹1 lakh","₹1–₹3 lakh","₹3–₹5 lakh","Above ₹5 lakh"];
const types:{id:EnquiryType;name:string;icon:typeof Gem}[]=[{id:"collection",name:"A collection",icon:Gem},{id:"custom",name:"Custom jewellery",icon:PencilRuler},{id:"appointment",name:"A showroom visit",icon:MapPin}];
const generalWhatsApp=whatsappUrl("Hello Nu Punjab Jewellery House, I would like to enquire about your jewellery.");

function Choice({id,label,value,options,onChange,hint}:{id:string;label:string;value:string;options:string[];onChange:(v:string)=>void;hint?:string}){
 return <div className="field"><label id={`${id}-label`} htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-labelledby={`${id}-label`} className="choice"><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>{hint&&<small>{hint}</small>}</div>;
}

export default function Home(){
 const[menu,setMenu]=useState(false),[filter,setFilter]=useState("all"),[draft,setDraft]=useState<RequestDraft>(initialDraft),[errors,setErrors]=useState<Record<string,string>>({}),[review,setReview]=useState(false),[copyStatus,setCopyStatus]=useState(""),[today,setToday]=useState("");
 const reviewHeading=useRef<HTMLHeadingElement>(null),formHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>setToday(indiaDate()),[]);
 useEffect(()=>{if(review)reviewHeading.current?.focus();},[review]);
 useEffect(()=>{if(!menu)return;const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);document.getElementById("menu-toggle")?.focus();}};window.addEventListener("keydown",esc);return()=>window.removeEventListener("keydown",esc);},[menu]);
 function change<K extends keyof RequestDraft>(key:K,value:RequestDraft[K]){setDraft(d=>({...d,[key]:value}));setErrors(e=>({...e,[key]:""}));setCopyStatus("");}
 function start(type:EnquiryType,collection?:string){setDraft(d=>({...d,type,...(collection?{collection}:{})}));setReview(false);setErrors({});setMenu(false);setTimeout(()=>{document.getElementById("enquire")?.scrollIntoView({behavior:"smooth",block:"start"});formHeading.current?.focus({preventScroll:true});},100);}
 function submit(e:FormEvent){e.preventDefault();const errs=validateDraft(draft);setErrors(errs);if(Object.keys(errs).length){setTimeout(()=>document.getElementById(Object.keys(errs)[0])?.focus(),20);return;}setReview(true);}
 async function copyMessage(){try{await navigator.clipboard.writeText(prepareMessage(draft));setCopyStatus("Message copied. Paste it into WhatsApp or email.");}catch{setCopyStatus("Select the message below to copy it manually.");}}
 useEffect(()=>{
  const context=(document as unknown as{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:"start_jewellery_enquiry",title:"Start jewellery enquiry",description:"Prepare the visible enquiry form. Does not send a message or book a visit.",inputSchema:{type:"object",properties:{type:{type:"string",enum:["collection","custom","appointment"]},collection:{type:"string",enum:collections.map(c=>c.name)}},required:["type"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as{type:EnquiryType;collection?:string};if(!v||!["collection","custom","appointment"].includes(v.type)||(v.collection&&!collections.some(c=>c.name===v.collection)))throw new Error("Invalid enquiry type or collection");setDraft(d=>({...d,type:v.type,...(v.collection?{collection:v.collection}:{})}));setReview(false);setErrors({});document.getElementById("enquire")?.scrollIntoView({behavior:"smooth"});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{status:"prepared",type:v.type,collection:v.collection??null};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 const error=(key:string)=>errors[key]&&<span className="error" id={`${key}-error`}>{errors[key]}</span>;
 const message=review?prepareMessage(draft):"";
 return <>
  <a href="#main" className="skip-link">Skip to content</a>
  <GoldRateTicker/>
  <header className="site-header"><a href="#top" className="brand" aria-label="Nu Punjab Jewellery House home"><img src="/images/logo-mark.png" alt=""/><span>NU PUNJAB<small>JEWELLERY HOUSE</small></span></a><button id="menu-toggle" className="menu-toggle" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="primary-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="primary-nav" className={menu?"nav open":"nav"} aria-label="Primary navigation"><a href="#collections" onClick={()=>setMenu(false)}>Collections</a><a href="#custom" onClick={()=>setMenu(false)}>Custom jewellery</a><a href="#heritage" onClick={()=>setMenu(false)}>Our heritage</a><a href="#visit" onClick={()=>setMenu(false)}>Visit us</a><button className="button nav-enquire" onClick={()=>start("custom")}>Enquire</button></nav></header>
  <main id="main">
   <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Gold. Diamonds. Your story.</p><h1>Jewels for every<br/><em>chapter of life.</em></h1><p className="hero-description">Fine gold and diamond jewellery, with a personal touch that makes it unmistakably yours.</p><div className="hero-actions"><a href="#collections" className="button gold-button">Explore collections</a><button className="underlined" onClick={()=>start("custom")}>Create something personal</button></div><div className="hero-heritage"><span>EST. 1994</span><span>A fourth-generation family legacy</span></div></div><div className="hero-visual"><img src="/images/hero-necklace.jpeg" alt="Diamond and gold necklace displayed on a model" fetchPriority="high"/><span className="image-caption">The art of celebrating you.</span></div></section>
   <div className="assurance"><span><ShieldCheck/>BIS hallmarked gold jewellery</span><span><Gem/>Diamond certification where applicable</span><span><PencilRuler/>Made around your vision</span></div>
   <section id="collections" className="section collections"><div className="section-heading"><div><p className="eyebrow">A piece for your moment</p><h2>Signature collections</h2></div><p>From everyday elegance to bridal splendour.<br/>Explore what speaks to you.</p></div><Tabs value={filter} onValueChange={setFilter} className="collection-tabs"><TabsList aria-label="Filter collections" className="filter-list">{[{id:"all",name:"All collections"},...collections.map(c=>({id:c.id,name:c.category}))].map(t=><TabsTrigger key={t.id} value={t.id}>{t.name}</TabsTrigger>)}</TabsList>{["all",...collections.map(c=>c.id)].map(t=><TabsContent key={t} value={t}><div className="collection-grid">{collections.filter(c=>t==="all"||c.id===t).map(c=><Dialog key={c.id}><DialogTrigger asChild><button className={`collection-card ${c.id}`} aria-label={`Explore ${c.name}`}><div className="collection-image"><img src={`/images/${c.image}`} alt={c.alt} loading="lazy"/><span className="collection-tag">{c.category}</span><span className="card-overlay">Explore the collection</span></div><div className="card-copy"><span className="card-number">0{collections.indexOf(c)+1}</span><div><h3>{c.name}</h3><p>{c.line}</p></div><span className="card-plus" aria-hidden="true">+</span></div></button></DialogTrigger><DialogContent className="collection-dialog"><img src={`/images/${c.image}`} alt={c.alt}/><div className="dialog-copy"><p className="eyebrow">{c.category} collection</p><DialogTitle>{c.name}</DialogTitle><DialogDescription>{c.description}</DialogDescription><ul>{c.details.map(d=><li key={d}><Check/>{d}</li>)}</ul><p className="small-note">Images are collection inspiration. Availability, specifications and pricing are confirmed personally.</p><DialogClose asChild><button className="button wine-button" onClick={()=>start("collection",c.name)}>Enquire about this collection</button></DialogClose></div></DialogContent></Dialog>)}</div><p className="collection-count" aria-live="polite">{t==="all"?"3 collections to explore":"1 collection to explore"} · Personal guidance, considered choices.</p></TabsContent>)}</Tabs></section>
   <section id="custom" className="custom-section"><div><p className="eyebrow">Made exclusively for you</p><h2>Your idea.<br/><em>Our craftsmanship.</em></h2><p>A first sketch, a cherished reference, or an heirloom ready for a new chapter. We bring your vision to life in gold and diamonds.</p><button className="button gold-button" onClick={()=>start("custom")}>Prepare your custom request</button></div><div className="custom-steps"><article><span>01</span><div><h3>Share your inspiration</h3><p>Tell us about the piece, your occasion and what makes it personal.</p></div></article><article><span>02</span><div><h3>Make thoughtful choices</h3><p>Discuss design, gold, diamonds and a budget that works for you.</p></div></article><article><span>03</span><div><h3>Craft your next heirloom</h3><p>Refine the details with our team before your piece is made.</p></div></article></div></section>
   <section id="enquire" className="section enquiry-section"><div className="section-heading"><div><p className="eyebrow">Let’s begin a conversation</p><h2 ref={formHeading} tabIndex={-1}>What brings you to us?</h2></div><p>A little about your idea helps us<br/>give you more personal guidance.</p></div><div className="enquiry-layout"><div className="enquiry-form-card">{!review?<><Tabs value={draft.type} onValueChange={v=>{change("type",v as EnquiryType);setErrors({});}}><TabsList aria-label="Choose your enquiry type" className="enquiry-types">{types.map(t=><TabsTrigger key={t.id} value={t.id}><t.icon/>{t.name}</TabsTrigger>)}</TabsList><TabsContent value={draft.type}><form onSubmit={submit} noValidate><div className="form-top"><span className="step-label">01 / YOUR DETAILS</span><p>{draft.type==="custom"?"Let’s shape your idea together.":draft.type==="appointment"?"Choose a preferred day to visit.":"Tell us which collection caught your eye."}</p></div><div className="form-grid">
    <div className="field"><label htmlFor="name">Your name <span aria-hidden="true">*</span></label><input id="name" name="name" autoComplete="name" required maxLength={80} placeholder="Your full name" value={draft.name} onChange={e=>change("name",e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name?"name-error":undefined}/>{error("name")}</div>
    <div className="field"><label htmlFor="phone">Phone number <span className="optional">(optional)</span></label><input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={24} placeholder="+91" value={draft.phone} onChange={e=>change("phone",e.target.value)} aria-invalid={!!errors.phone} aria-describedby={errors.phone?"phone-error":undefined}/>{error("phone")}</div>
    {draft.type!=="custom"&&<Choice id="collection" label={draft.type==="appointment"?"Interested in":"Choose a collection"} value={draft.collection} options={[...collections.map(c=>c.name),"Custom jewellery","Help me choose"]} onChange={v=>change("collection",v)}/>}
    {draft.type==="custom"&&<><Choice id="piece" label="What would you like to create?" value={draft.piece} options={["Ring","Necklace","Earrings","Bracelet / bangle","Pendant","Bridal set","Redesign an heirloom","Something else"]} onChange={v=>change("piece",v)}/><Choice id="metal" label="Preferred metal" value={draft.metal} options={["Guide me","Yellow gold","White gold","Rose gold"]} onChange={v=>change("metal",v)}/><Choice id="stones" label="Stones & details" value={draft.stones} options={["Guide me","Natural diamonds","Lab-grown diamonds — enquire","Coloured gemstones","All gold, no stones"]} onChange={v=>change("stones",v)}/><Choice id="timing" label="When do you need it?" value={draft.timing} options={["Flexible","Within 1 month","In 1–3 months","More than 3 months away"]} onChange={v=>change("timing",v)} hint="Our team will confirm what’s possible for your design."/></>}
    {draft.type!=="appointment"&&<Choice id="budget" label="Approximate budget" value={draft.budget} options={budgets} onChange={v=>change("budget",v)} hint="A starting point for the conversation, not a quotation."/>}
    {draft.type==="appointment"&&<><div className="field"><label htmlFor="date">Preferred visit date <span aria-hidden="true">*</span></label><input id="date" name="date" type="date" required min={today||undefined} value={draft.date} onChange={e=>change("date",e.target.value)} aria-invalid={!!errors.date} aria-describedby={errors.date?"date-hint date-error":"date-hint"}/><small id="date-hint">11 AM–8 PM. Closed Wednesday.</small>{error("date")}</div><Choice id="time" label="Preferred time" value={draft.time} options={["Flexible within showroom hours","11 AM–1 PM","1 PM–3 PM","3 PM–5 PM","5 PM–7 PM"]} onChange={v=>change("time",v)}/></>}
    {draft.type==="custom"&&<div className="field full"><label htmlFor="reference">Inspiration link <span className="optional">(optional)</span></label><input id="reference" name="reference" type="url" placeholder="https://…" maxLength={1500} value={draft.reference} onChange={e=>change("reference",e.target.value)} aria-invalid={!!errors.reference} aria-describedby={errors.reference?"reference-hint reference-error":"reference-hint"}/><small id="reference-hint">Or send your sketch or photos in WhatsApp after reviewing your request.</small>{error("reference")}</div>}
    <div className="field full"><label htmlFor="notes">{draft.type==="custom"?"Tell us about your idea":"Anything else you’d like us to know?"} {draft.type==="custom"?<span aria-hidden="true">*</span>:<span className="optional">(optional)</span>}</label><textarea id="notes" name="notes" rows={3} required={draft.type==="custom"} maxLength={1200} placeholder={draft.type==="custom"?"Your occasion, preferred style, dimensions, or details you love…":"Your occasion, questions or preferences…"} value={draft.notes} onChange={e=>change("notes",e.target.value)} aria-invalid={!!errors.notes} aria-describedby={errors.notes?"notes-error":undefined}/>{error("notes")}</div>
   </div><div className="form-actions"><button type="submit" className="button wine-button">Review your request</button><small>Nothing is sent until you send your message in WhatsApp.</small></div></form></TabsContent></Tabs></>:<div className="review"><span className="step-label">02 / REVIEW & CONNECT</span><h3 ref={reviewHeading} tabIndex={-1}>Your conversation starts here.</h3><p>Check your details, then continue to WhatsApp to send your request. {draft.type==="appointment"?"Your visit is only booked once our team confirms availability.":"Our team will discuss the details and pricing with you personally."}</p><pre className="message-preview">{message}</pre><div className="review-actions"><a className="button wine-button" href={whatsappUrl(message)} target="_blank" rel="noreferrer"><MessageCircle/>Continue to WhatsApp</a><button className="button outline-button" onClick={copyMessage}><Copy/>Copy message</button></div><p role="status" className="copy-status">{copyStatus}</p><button className="underlined edit-request" onClick={()=>{setReview(false);setCopyStatus("");setTimeout(()=>formHeading.current?.focus(),20);}}>Edit your request</button><p className="small-note">Prefer email? Copy your message and send it to <a href="mailto:info@nupunjabjewelleryhouse.com">info@nupunjabjewelleryhouse.com</a>.</p></div>}</div><aside className="enquiry-aside"><Sparkles className="aside-sparkle"/><p className="eyebrow">The Nu Punjab promise</p><h3>Jewellery is personal.<br/><em>So is our service.</em></h3><p>Thoughtful design. Transparent conversations. The care of a family jeweller, since 1994.</p><div className="aside-facts"><div><strong>4th</strong><span>Generation family business</span></div><div><strong>30+</strong><span>Years of trust</span></div></div><a href="tel:+919818208000" className="aside-phone"><Phone/>+91 98182 08000</a><small>Prefer a conversation? Call us during showroom hours.</small></aside></div></section>
   <InstagramFeed/>
   <section id="heritage" className="heritage-section"><div><p className="eyebrow">A legacy of trust</p><h2>Rooted in Punjab.<br/><em>Loved in Delhi.</em></h2></div><div><p>For over three decades, Nu Punjab Jewellery House has helped families mark life’s most meaningful moments with honest guidance, enduring quality and a personal touch.</p><p>Now run by the fourth generation of our family, we carry the same craft and care forward with every piece.</p><a href="https://www.instagram.com/nupunjabjewelleryhouse/" target="_blank" rel="noreferrer" className="underlined instagram-link"><Camera/>Follow our jewellery stories</a></div></section>
   <section id="visit" className="section visit-section"><div><p className="eyebrow">Come, find your piece</p><h2>We’d love to<br/>welcome you.</h2><p>Experience our collections in person.<br/>Let’s find jewellery for your moment.</p><button className="button wine-button" onClick={()=>start("appointment")}>Request a showroom visit</button></div><div className="visit-details"><div className="visit-row"><MapPin/><div><h3>Our showroom</h3><address>F-118, Main Market, Rajouri Garden<br/>New Delhi 110027, India</address><a href="https://maps.app.goo.gl/VNbsMiJzc6GAscj59" target="_blank" rel="noreferrer" className="underlined">Get directions</a></div></div><div className="visit-row"><Clock3/><div><h3>11:00 AM–8:00 PM</h3><p>Monday–Tuesday & Thursday–Sunday<br/><strong>Closed Wednesday</strong></p></div></div><div className="visit-row"><Phone/><div><a className="contact-phone" href="tel:+919818208000">+91 98182 08000</a><a className="contact-email" href="mailto:info@nupunjabjewelleryhouse.com">info@nupunjabjewelleryhouse.com</a></div></div></div></section>
  </main>
  <footer><div className="footer-main"><a href="#top" className="footer-brand">NU PUNJAB<span>JEWELLERY HOUSE</span><small>ESTABLISHED 1994</small></a><p>Let’s find something<br/><em>beautiful together.</em></p><div><a href={generalWhatsApp} target="_blank" rel="noreferrer" className="button gold-button"><MessageCircle/>WhatsApp us</a><a href="https://www.instagram.com/nupunjabjewelleryhouse/" target="_blank" rel="noreferrer">@nupunjabjewelleryhouse</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nu Punjab Jewellery House</span><a href="#collections">Collections</a><a href="#enquire">Enquiries</a><a href="#visit">Visit us</a></div><p id="rate-note" className="rate-disclaimer">Gold and silver rates are indicative IBJA-based rates per gram, including 3% GST, from our current rate source. Final billing includes making charges and applicable wastage; confirm your quotation with our team.</p></footer><a href={generalWhatsApp} target="_blank" rel="noreferrer" className="whatsapp-float" aria-label="Chat with Nu Punjab Jewellery House on WhatsApp"><MessageCircle/><span>Let’s talk</span></a>
 </>;
}
