import {build} from 'esbuild';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);
const hash=s=>createHash('sha256').update(s).digest('hex').slice(0,12);
await mkdir('.build',{recursive:true});await mkdir('dist/assets',{recursive:true});await mkdir('dist/images',{recursive:true});
for(const name of ['hero-necklace.jpeg','gold-heirlooms.jpeg','diamond-earring.png','gold-jewellery.png','logo-mark.png','favicon.png'])await copyFile('images/'+name,'dist/images/'+name);
for(const name of ['robots.txt','sitemap.xml'])await copyFile(name,'dist/'+name);
const css=await postcss([tailwindcss({base:resolve('source')})]).process(await readFile('source/app/globals.css','utf8'),{from:resolve('source/app/globals.css'),map:false});
const cssName=`jewellery-${hash(css.css)}.css`;await writeFile('dist/assets/'+cssName,css.css);
const js=await build({entryPoints:['source/client.tsx'],bundle:true,write:false,format:'esm',platform:'browser',minify:true,jsx:'automatic',tsconfig:'tsconfig.json',target:['es2020'],define:{'process.env.NODE_ENV':'"production"'}});
const jsBytes=js.outputFiles[0].contents,jsName=`jewellery-${hash(jsBytes)}.js`;await writeFile('dist/assets/'+jsName,jsBytes);
await build({entryPoints:['source/app/page.tsx'],bundle:true,outfile:'.build/render.cjs',platform:'node',format:'cjs',packages:'external',jsx:'automatic',tsconfig:'tsconfig.json'});
const require=createRequire(import.meta.url),React=require('react'),{renderToString}=require('react-dom/server'),Home=require(resolve('.build/render.cjs')).default;
const content=renderToString(React.createElement(Home)),head=await readFile('source/head.html','utf8');
await writeFile('dist/index.html',`<!doctype html><html lang="en"><head>${head}<link rel="stylesheet" href="/assets/${cssName}"></head><body><div id="app">${content}</div><script type="module" src="/assets/${jsName}"></script></body></html>`);
await build({entryPoints:['source/functions/site-gold-rates.ts'],outfile:'netlify/functions/site-gold-rates.js',bundle:true,platform:'node',format:'cjs',external:['./gold-rate.js'],target:'node22',tsconfig:'tsconfig.json'});
console.log(JSON.stringify({status:'built',html:'dist/index.html',css:'dist/assets/'+cssName,js:'dist/assets/'+jsName}));
